module.exports = {

    // Success
    SUCCESS : { "isSuccess": true, "code": 1000, "message":"성공" },
    SUCCESS_JOIN : { "isSuccess": true, "code": 1001, "message":"회원가입 성공" },
    SUCCESS_LOGIN : { "isSuccess": true, "code": 1002, "message":"로그인 성공" },
    SUCCESS_SELECT_USER : { "isSuccess": true, "code": 1003, "message":"유저조회 성공" },
    SUCCESS_MODIFY_USER : { "isSuccess": true, "code": 1004, "message":"유저정보 수정 성공" },
    SUCCESS_STATUS_USER : { "isSuccess": true, "code": 1005, "message":"유저상태 변경 성공" },
    // SUCCESS_CATEGORY : { "isSuccess": true, "code": 1006, "message":"카테고리 등록 성공" },
    // SUCCESS_CATEGORY_PERSON : { "isSuccess": true, "code": 1007, "message":"카테고리에 숙박인원 등록 성공" },
    // SUCCESS_CATEGORY_BEDTYPE : { "isSuccess": true, "code": 1008, "message":"카테고리에 침실 유형 등록 성공" },
    // SUCCESS_LOCATION : { "isSuccess": true, "code": 1009, "message":"호스트 위치 등록 성공" },
    // SUCCESS_AMENITIES : { "isSuccess": true, "code": 1010, "message":"호스트 위치 등록 성공" },
    SUCCESS_HOST_PHOTO : { "isSuccess": true, "code": 1011, "message":"호스트 사진 등록 성공" },
    // SUCCESS_RESERVATION : { "isSuccess": true, "code": 1012, "message":"호스트 예약 설정 등록 성공" },
    SUCCESS_USER_RESERVATION : { "isSuccess": true, "code": 1013, "message":"예약 등록 성공" },
    SUCCESS_AVARIABLE_RESERVATION : { "isSuccess": true, "code": 1014, "message":"호스트 예약가능 여부 등록 성공" },
    SUCCESS_HOST_PRICE : { "isSuccess": true, "code": 1015, "message":"호스트 요금 등록 성공" },
    SUCCESS_HOST_LIST : { "isSuccess": true, "code": 1016, "message":"호스트 조회 성공" },
    SUCCESS_HOST_STATE_LIST : { "isSuccess": true, "code": 1017, "message":"해당 호스트 지역 조회 성공" },
    SUCCESS_HOST_INFO_MODIFY : { "isSuccess": true, "code": 1018, "message":"호스트 정보 수정 성공" },
    SUCCESS_HOST_CATEGORY_MODIFY : { "isSuccess": true, "code": 1019, "message":"호스트 카테고리 수정 성공" },
    SUCCESS_CATEGORY_PERSON_MODIFY : { "isSuccess": true, "code": 1020, "message":"카테고리 인원 설정 수정 성공" },
    SUCCESS_CATEGORY_BEDROOM_MODIFY : { "isSuccess": true, "code": 1021, "message":"카테고리 침실유형 설정 수정 성공" },
    SUCCESS_HOST_LOCATION_MODIFY : { "isSuccess": true, "code": 1022, "message":"호스트 위치 설정 수정 성공" },
    SUCCESS_HOST_AMENITIES_MODIFY : { "isSuccess": true, "code": 1023, "message":"호스트 편의시설 설정 수정 성공" },
    SUCCESS_HOST_PHOTO_DELETE : { "isSuccess": true, "code": 1024, "message":"호스트 사진 삭제 성공" },
    SUCCESS_HOST_RESERVATION_MODIFY : { "isSuccess": true, "code": 1025, "message":"호스트 예약 설정 수정 성공" },
    SUCCESS_HOST_PRICE_MODIFY : { "isSuccess": true, "code": 1026, "message":"호스트 요금 설정 수정 성공" },
    SUCCESS_HOST_STATUE_MODIFY : { "isSuccess": true, "code": 1027, "message":"호스트 상태 수정 성공" },
    SUCCESS_SEARCH_USER_HOST : { "isSuccess": true, "code": 1028, "message":"유저가 찾는 호스트 검색 성공" },
    SUCCESS_LASTTRIP_MODIFY : { "isSuccess": true, "code": 1029, "message":"지난 여행으로 업데이트 성공" },
    SUCCESS_LASTTRIP_DELETE : { "isSuccess": true, "code": 1030, "message":"등록된 예약 삭제 성공" },
    SUCCESS_WISH_HOST : { "isSuccess": true, "code": 1031, "message":"해당 호스트 위시리스트 등록 성공" },
    SUCCESS_WISH_STATUS_MODIFY : { "isSuccess": true, "code": 1032, "message":"해당 호스트 위시리스트 상태값 변경 성공" },
    SUCCESS_WISHLIST_USER : { "isSuccess": true, "code": 1033, "message":"위시리스트 조회 성공" },
    SUCCESS_HOST : { "isSuccess": true, "code": 1034, "message":"호스트리스트 등록 성공" },
    SUCCESS_USER_RESERVATION_SELECT : { "isSuccess": true, "code": 1035, "message":"유저 예약리스트 조회 성공" },
    SUCCESS_WISHLIST : { "isSuccess": true, "code": 1036, "message":"위시리스트 등록 성공" },
    SUCCESS_WISHLIST_DELETE : { "isSuccess": true, "code": 1037, "message":"위시리스트 삭제 성공" },
    SUCCESS_MESSAGE_SEND : { "isSuccess": true, "code": 1038, "message":"메세지 보내기 성공" },
    SUCCESS_MESSAGE_SELECT : { "isSuccess": true, "code": 1039, "message":"메세지 조회 성공" },
    SUCCESS_USER_REVIEW : { "isSuccess": true, "code": 1040, "message":"리뷰 등록 성공" },
    SUCCESS_REVIEW_HOST_SELECT : { "isSuccess": true, "code": 1041, "message":"호스트 리뷰 조회 성공" },
    SUCCESS_REVIEW_MODIFY : { "isSuccess": true, "code": 1042, "message":"리뷰 수정 성공" },
    SUCCESS_REVIEW_STATUS : { "isSuccess": true, "code": 1043, "message":"리뷰 삭제 성공" },
    SUCCESS_NOTICE_USER : { "isSuccess": true, "code": 1044, "message":"알림 등록 성공" },
    SUCCESS_NOTICE_USER_SELECT : { "isSuccess": true, "code": 1045, "message":"유저 알림 조회 성공" },
    SUCCESS_NOTICE_DELETE : { "isSuccess": true, "code": 1046, "message":"유저 알림 삭제 성공" },
    SUCCESS_WISH_MODIFY : { "isSuccess": true, "code": 1047, "message":"위시리스트 수정 성공" },
    SUCCESS_HOST_DELETE : { "isSuccess": true, "code": 1048, "message":"호스트 삭제 성공" },
    SUCCESS_MESSAGE_DELETE : { "isSuccess": true, "code": 1049, "message":"메시지 삭제 성공" },

    FAIL_GOOGLE_LOGIN : {"isSuccess": false, "code": 1800, "message":"구글 로그인 인증 실패"},
    SUCCESS_GOOGLE_LOGIN : { "isSuccess": true, "code": 1801, "message":"구글 로그인 인증 성공" },


    // Common
    TOKEN_EMPTY : { "isSuccess": false, "code": 2000, "message":"JWT 토큰을 입력해주세요." },
    TOKEN_VERIFICATION_FAILURE : { "isSuccess": false, "code": 3000, "message":"JWT 토큰 검증 실패" },
    TOKEN_VERIFICATION_SUCCESS : { "isSuccess": true, "code": 1001, "message":"JWT 토큰 검증 성공" }, // ?
    TOKEN_GOOGLE_EMPTY : { "isSuccess": false, "code": 3500, "message":"구글 ACCESS 토큰을 입력해주세요." },
    TOKEN_GOOGLE_PARAMS_EMPTY : { "isSuccess": false, "code": 3501, "message":"파라미터에 구글 ACCESS 토큰을 입력해주세요." },


    //Request error
    SIGNUP_EMAIL_EMPTY : { "isSuccess": false, "code": 2001, "message":"이메일을 입력해주세요." },
    SIGNUP_EMAIL_LENGTH : { "isSuccess": false, "code": 2002, "message":"이메일은 30자리 미만으로 입력해주세요." },
    SIGNUP_EMAIL_ERROR_TYPE : { "isSuccess": false, "code": 2003, "message":"이메일 형식을 정확하게 입력해주세요." },
    SIGNUP_PASSWORD_EMPTY : { "isSuccess": false, "code": 2004, "message": "비밀번호를 입력해주세요." },
    SIGNUP_PASSWORD_LENGTH : { "isSuccess": false, "code": 2005, "message":"비밀번호는 최소 8자리 이상 입력해주세요." },
    SIGNUP_PASSWORD_ERROR_TYPE : { "isSuccess": false, "code": 2006, "message":"비밀번호는 기호나 숫자가 1개 이상 들어가야 합니다." },
    SIGNUP_FIRSTNAME_EMPTY : { "isSuccess": false, "code": 2007, "message":"성을 입력해주세요." },
    SIGNUP_FIRSTNAME_LENGTH : { "isSuccess": false, "code": 2008, "message":"성은 30자리 미만으로 입력해주세요." },
    SIGNUP_SECONDNAME_EMPTY : { "isSuccess": false, "code": 2009, "message":"이름을 입력해주세요." },
    SIGNUP_SECONDNAME_LENGTH : { "isSuccess": false, "code": 2010, "message":"이름은 40자리 미만으로 입력해주세요." },
    SIGNUP_BIRTH_EMPTY : { "isSuccess": false, "code": 2011, "message":"생년월일을 입력해주세요." },
    SIGNUP_BIRTH_ERROR_TYPE : { "isSuccess": false, "code": 2012, "message":"생년월일 형식을 정확하게 입력해주세요." },
    SIGNUP_PHONE_EMPTY : { "isSuccess": false, "code": 2013, "message":"휴대폰 번호를 입력해주세요." },
    SIGNUP_PHONE_LENGTH : { "isSuccess": false, "code": 2014, "message":"휴대폰 번호는 20자리 미만으로 입력해주세요." },
    SIGNUP_PHONE_ERROR_TYPE : { "isSuccess": false, "code": 2015, "message":"휴대폰 번호 형식을 정확하게 입력해주세요." },
    SIGNUP_GENDER_EMPTY : { "isSuccess": false, "code": 2016, "message":"성별을 입력해주세요." },
    SIGNUP_GENDER_ERROR_TYPE : { "isSuccess": false, "code": 2017, "message":"성별은 M 또는 W로 입력해주세요." },
    SIGNUP_STATUS_EMPTY : { "isSuccess": false, "code": 2018, "message":"유저 상태값을 입력해주세요." },
    SIGNUP_STATUS_ERROR_TYPE : { "isSuccess": false, "code": 2019, "message":"ACTIVE, LOCK, DELETE로 입력해주세요." },
    SIGNUP_HOST_STATUS_EMPTY : { "isSuccess": false, "code": 2020, "message":"호스트 상태값을 입력해주세요." },
    SIGNUP_HOST_STATUS_ERROR_TYPE : { "isSuccess": false, "code": 2021, "message":"호스트 상태값은 Y, N으로 입력해주세요." },
    SIGNUP_PHOTO_STATUS_EMPTY : { "isSuccess": false, "code": 2022, "message":"호스트 이미지 상태값을 입력해주세요." },
    SIGNUP_TRIP_ISLAST_EMPTY : { "isSuccess": false, "code": 2023, "message":"숙박 이용여부 상태값을 입력해주세요." },
    SIGNUP_TRIP_ISLAST_ERROR_TYPE : { "isSuccess": false, "code": 2024, "message":"숙박 이용여부 상태값은 Y, N으로 입력해주세요." },
    SIGNUP_MESSAGE_STATUS_EMPTY : { "isSuccess": false, "code": 2025, "message":"메세지 상태값을 입력해주세요." },
    SIGNUP_MESSAGE_ERROR_TYPE : { "isSuccess": false, "code": 2026, "message":"메세지 상태값은 Y, N으로 입력해주세요." },
    SIGNUP_REVIEW_RATING_EMPTY : { "isSuccess": false, "code": 2027, "message":"리뷰 평점을 입력해주세요." },
    SIGNUP_REVIEW_RATING_LENGTH : { "isSuccess": false, "code": 2028, "message":"평점은 5점 이하로 입력해주세요." },
    SIGNUP_REVIEW_MESSAGE_EMPTY : { "isSuccess": false, "code": 2029, "message":"리뷰 메세지를 입력해주세요." },
    SIGNUP_NOTICE_STATUS_EMPTY : { "isSuccess": false, "code": 2030, "message":"알림 상태값을 입력해주세요." },
    SIGNUP_NOTICE_STATUS_ERROR_TYPE : { "isSuccess": false, "code": 2031, "message":"알림 상태값은 Y, N으로 입력해주세요." },
    SIGNUP_NOTICE_STATUS_ERROR_FORM : { "isSuccess": false, "code": 2032, "message":"알림 상태값은 숫자 입력이 불가합니다." },


    SIGNIN_EMAIL_EMPTY : { "isSuccess": false, "code": 2500, "message":"이메일을 입력해주세요." },
    SIGNIN_EMAIL_LENGTH : { "isSuccess": false, "code": 2501, "message":"이메일은 30자리 미만으로 입력해주세요." },
    SIGNIN_EMAIL_ERROR_TYPE : { "isSuccess": false, "code": 2502, "message":"이메일을 형식을 정확하게 입력해주세요." },
    SIGNIN_PHONE_EMPTY : { "isSuccess": false, "code": 2503, "message":"휴대폰 번호를 입력해주세요." },
    SIGNIN_PHONE_ERROR_TYPE : { "isSuccess": false, "code": 2504, "message":"휴대폰 번호 형식을 정확하게 입력해주세요." },
    SIGNIN_PASSWORD_EMPTY : { "isSuccess": false, "code": 2505, "message": "비밀번호를 입력 해주세요." },
    SIGNIN_PASSWORD_ERROR_TYPE : { "isSuccess": false, "code": 2506, "message":"비밀번호 형식이 잘못되었습니다." },
    SIGNIN_HOST_NAME_EMPTY : { "isSuccess": false, "code": 2507, "message":"호스트 제목을 입력해주세요." },
    SIGNIN_HOST_NAME_LENGTH: { "isSuccess": false, "code": 2508, "message":"호스트 제목을 50자리 미만으로 입력해주세요." },
    SIGNIN_CATEGORY_ACCTYPE_EMPTY: { "isSuccess": false, "code": 2509, "message":"숙소 건물 유형을 입력해주세요." },
    SIGNIN_CATEGORY_ACCTYPEDETAIL_EMPTY: { "isSuccess": false, "code": 2510, "message":"구체적인 숙소 유형을 입력해주세요." },
    SIGNIN_CATEGORY_TYPEHOUSE_EMPTY: { "isSuccess": false, "code": 2511, "message":"숙소 유형을 입력해주세요." },
    SIGNIN_CATEGORY_GUEST_EMPTY: { "isSuccess": false, "code": 2512, "message":"게스트 전용 여부를 입력해주세요." },
    SIGNIN_CATEGORY_GUESTCNT_EMPTY: { "isSuccess": false, "code": 2513, "message":"숙박 인원을 입력해주세요." },
    SIGNIN_CATEGORY_GUESTCNT_LENGTH: { "isSuccess": false, "code": 2514, "message":"숙박 인원은 17미만으로 입력해주세요." },
    SIGNIN_CATEGORY_BEDROOMCNT_EMPTY: { "isSuccess": false, "code": 2515, "message":"침실 갯수를 입력해주세요." },
    SIGNIN_CATEGORY_BEDROOMCNT_LENGTH: { "isSuccess": false, "code": 2516, "message":"침실 갯수를 17미만으로 입력해주세요." },
    SIGNIN_CATEGORY_COUCHCNT_EMPTY: { "isSuccess": false, "code": 2517, "message":"카우치 갯수를 입력해주세요." },
    SIGNIN_CATEGORY_COUCHCNT_LENGTH: { "isSuccess": false, "code": 2518, "message":"카우치 갯수를 6미만으로 입력해주세요." },
    SIGNIN_CATEGORY_SINGLECNT_EMPTY: { "isSuccess": false, "code": 2519, "message":"싱글 갯수를 입력해주세요." },
    SIGNIN_CATEGORY_SINGLECNT_LENGTH: { "isSuccess": false, "code": 2520, "message":"싱글 갯수를 6미만으로 입력해주세요." },
    SIGNIN_CATEGORY_SMALLDOUBLEDCNT_EMPTY: { "isSuccess": false, "code": 2521, "message":"스몰더블 갯수를 입력해주세요." },
    SIGNIN_CATEGORY_SMALLDOUBLEDCNT_LENGTH: { "isSuccess": false, "code": 2522, "message":"스몰더블 갯수를 6미만으로 입력해주세요." },
    SIGNIN_CATEGORY_DOUBLECNT_EMPTY: { "isSuccess": false, "code": 2523, "message":"더블 갯수를 입력해주세요." },
    SIGNIN_CATEGORY_DOUBLECNT_LENGTH: { "isSuccess": false, "code": 2524, "message":"더블 갯수를 6미만으로 입력해주세요." },
    SIGNIN_CATEGORY_QUEENCNT_EMPTY: { "isSuccess": false, "code": 2525, "message":"퀸 갯수를 입력해주세요." },
    SIGNIN_CATEGORY_QUEENCNT_LENGTH: { "isSuccess": false, "code": 2526, "message":"퀸 갯수를 6미만으로 입력해주세요." },
    SIGNIN_CATEGORY_KINGCNT_EMPTY: { "isSuccess": false, "code": 2527, "message":"킹 갯수를 입력해주세요." },
    SIGNIN_CATEGORY_KINGCNT_LENGTH: { "isSuccess": false, "code": 2528, "message":"킹 갯수를 6미만으로 입력해주세요." },
    SIGNIN_CATEGORY_BUNKBEDCNT_EMPTY: { "isSuccess": false, "code": 2529, "message":"이층침대 갯수를 입력해주세요." },
    SIGNIN_CATEGORY_BUNKBEDCNT_LENGTH: { "isSuccess": false, "code": 2530, "message":"이층침대 갯수를 6미만으로 입력해주세요." },
    SIGNIN_HOST_LOCATION_COUNTRY_EMPTY: { "isSuccess": false, "code": 2531, "message":"국가를 입력해주세요." },
    SIGNIN_HOST_LOCATION_STATE_EMPTY: { "isSuccess": false, "code": 2532, "message":"지역을 입력해주세요." },
    SIGNIN_HOST_LOCATION_CITY_EMPTY: { "isSuccess": false, "code": 2533, "message":"도시를 입력해주세요." },
    SIGNIN_HOST_LOCATION_STREET_EMPTY: { "isSuccess": false, "code": 2534, "message":"주소를 입력해주세요." },
    SIGNIN_HOST_LOCATION_ZIP_EMPTY: { "isSuccess": false, "code": 2535, "message":"우편번호를 입력해주세요." },
    SIGNIN_HOST_LOCATION_ZIP_ERROR_TYPE: { "isSuccess": false, "code": 2536, "message":"우편번호 형식이 잘못되었습니다." },
    SIGNIN_HOST_AMENITIES_WIFI_EMPTY: { "isSuccess": false, "code": 2537, "message":"와이파이 유무를 입력해주세요." },
    SIGNIN_HOST_AMENITIES_WIFI_ERROR_TYPE: { "isSuccess": false, "code": 2538, "message":"와이파이 타입이 잘못되었습니다." },
    SIGNIN_HOST_AMENITIES_AIRCONDITIONING_EMPTY: { "isSuccess": false, "code": 2539, "message":"에어컨 유무를 입력해주세요." },
    SIGNIN_HOST_AMENITIES_AIRCONDITIONING_ERROR_TYPE: { "isSuccess": false, "code": 2540, "message":"에어컨 타입이 잘못되었습니다." },
    SIGNIN_HOST_AMENITIES_HAIRDRYER_EMPTY: { "isSuccess": false, "code": 2541, "message":"헤어드라이기 유무를 입력해주세요." },
    SIGNIN_HOST_AMENITIES_HAIRDRYER_ERROR_TYPE: { "isSuccess": false, "code": 2542, "message":"헤어드라이기 타입이 잘못되었습니다." },
    SIGNIN_HOST_AMENITIES_KITCHEN_EMPTY: { "isSuccess": false, "code": 2543, "message":"주방 유무를 입력해주세요." },
    SIGNIN_HOST_AMENITIES_KITCHEN_ERROR_TYPE: { "isSuccess": false, "code": 2544, "message":"주방 타입이 잘못되었습니다." },
    SIGNIN_HOST_AMENITIES_WASHER_EMPTY: { "isSuccess": false, "code": 2545, "message":"샤워기 유무를 입력해주세요." },
    SIGNIN_HOST_AMENITIES_WASHER_ERROR_TYPE: { "isSuccess": false, "code": 2546, "message":"샤워기 타입이 잘못되었습니다." },
    SIGNIN_HOST_IMG_EMPTY: { "isSuccess": false, "code": 2547, "message":"호스트 이미지를 입력해주세요." },
    SIGNIN_HOST_RESERVATION_NOTICE_EMPTY: { "isSuccess": false, "code": 2548, "message":"호스트 예약마감 기한을 입력해주세요." },
    SIGNIN_HOST_RESERVATION_NOTICE_ERROR_TYPE: { "isSuccess": false, "code": 2549, "message":"호스트 예약마감 타입이 잘못되었습니다." },
    SIGNIN_HOST_RESERVATION_REQ_EMPTY: { "isSuccess": false, "code": 2550, "message":"예약 요청 기한을 입력해주세요." },
    SIGNIN_HOST_RESERVATION_REQ_ERROR_TYPE: { "isSuccess": false, "code": 2551, "message":"예약 요청 기한의 타입이 잘못되었습니다." },
    SIGNIN_HOST_RESERVATION_AVAILABLITYWINDOW_EMPTY: { "isSuccess": false, "code": 2552, "message":"예약 가능한 기간여부를 입력해주세요." },
    SIGNIN_HOST_RESERVATION_AVAILABLITYWINDOW_ERROR_TYPE: { "isSuccess": false, "code": 2553, "message":"예약 가능한 기간여부의 타입이 잘못되었습니다." },
    SIGNIN_HOST_RESERVATION_ARRIVEAFTER_EMPTY: { "isSuccess": false, "code": 2554, "message":"시각 후 체크인을 입력해주세요." },
    SIGNIN_HOST_RESERVATION_ARRIVEAFTER_ERROR_TYPE: { "isSuccess": false, "code": 2555, "message":"시각 후 체크인의 타입이 잘못되었습니다." },
    SIGNIN_HOST_RESERVATION_LEAVEBEFORE_EMPTY: { "isSuccess": false, "code": 2556, "message":"시각 전 체크아웃을 입력해주세요." },
    SIGNIN_HOST_RESERVATION_LEAVEBEFORE_ERROR_TYPE: { "isSuccess": false, "code": 2557, "message":"시각 전 체크아웃을 12 ~ 21로 입력해주세요." },
    SIGNIN_HOST_RESERVATION_MINSTAY_EMPTY: { "isSuccess": false, "code": 2558, "message":"최소 숙박을 입력해주세요." },
    SIGNIN_HOST_RESERVATION_MINSTAY_ERROR_FORM: { "isSuccess": false, "code": 2559, "message":"최소 숙박이 잘못 입력되었습니다." },
    SIGNIN_HOST_RESERVATION_MAXSTAY_EMPTY: { "isSuccess": false, "code": 2560, "message":"최대 숙박을 입력해주세요." },
    SIGNIN_HOST_RESERVATION_MAXSTAY_ERROR_FORM: { "isSuccess": false, "code": 2561, "message":"최대 숙박 잘못 입력해주세요." },
    SIGNIN_HOST_RESERVATION_RESERVATIONREQ_EMPTY: { "isSuccess": false, "code": 2562, "message":"예약요청 허용 여부를 입력해주세요." },
    SIGNIN_HOST_RESERVATION_RESERVATIONREQ_ERROR_TYPE: { "isSuccess": false, "code": 2563, "message":"예약요청 허용 여부의 타입이 잘못되었습니다." },
    SIGNIN_HOST_PRICE_EMPTY: { "isSuccess": false, "code": 2564, "message":"호스트 가격을 입력해주세요." },
    SIGNIN_HOST_PRICE_ERROR_FORM: { "isSuccess": false, "code": 2565, "message":"가격 형식이 잘못되었습니다." },
    SIGNIN_TRIP_STATUS_EMPTY: { "isSuccess": false, "code": 2566, "message":"숙박 예약의 상태값을 입력해주세요." },
    SIGNIN_TRIP_STATUS_ERROR_TYPE: { "isSuccess": false, "code": 2567, "message":"숙박 예약의 타입값이 잘못되었습니다." },
    SIGNIN_WISHLIST_TITLE_EMPTY: { "isSuccess": false, "code": 2568, "message":"위시리스트 제목을 입력해주세요. " },
    SIGNIN_WISHLIST_TITLE_LENGTH: { "isSuccess": false, "code": 2569, "message":"위시리스트 제목은 50자 미만으로 입력해주세요. " },
    SIGNIN_STARTDATE_EMPTY: { "isSuccess": false, "code": 2570, "message":"숙박 시작날짜를 입력해주세요. " },
    SIGNIN_STARTDATE_ERROR_TYPE: { "isSuccess": false, "code": 2571, "message":"시작날짜 형식이 잘못되었습니다." },
    SIGNIN_STARTDATE_ERROR_MATCH: { "isSuccess": false, "code": 2572, "message":"호스트가 등록한 날짜보다 이전은 입력할 수 없습니다." },
    SIGNIN_ENDDATE_EMPTY: { "isSuccess": false, "code": 2573, "message":"숙박 마지막 날짜를 입력해주세요. " },
    SIGNIN_ENDDATE_ERROR_TYPE: { "isSuccess": false, "code": 2574, "message":"마지막 날짜 형식이 잘못되었습니다." },
    SIGNIN_ENDDATE_ERROR_MATCH: { "isSuccess": false, "code": 2575, "message":"마지막 날짜는 시작날짜보다 이전은 입력할 수 없습니다." },
    SIGNIN_SEARCH_GUESTCNT_EMPTY: { "isSuccess": false, "code": 2576, "message":"검색에 필요한 숙박 게스트 수를 입력해주세요." },
    SIGNIN_SEARCH_GUESTCNT_LENGTH: { "isSuccess": false, "code": 2577, "message":"게스트 수는 21미만으로 입력해주세요." },
    SIGNIN_CATEGORY_GUEST_ERROR_TYPE: { "isSuccess": false, "code": 2578, "message":"게스트 전용 여부는 Y, N으로 입력해주세요." },
    SIGNIN_USER_RESERVATION_GUESTCNT_EMPTY: { "isSuccess": false, "code": 2579, "message":"예약할 숙박 게스트 수를 입력해주세요." },
    SIGNIN_TRIP_STATUS_DELETE_ERROR_TYPE: { "isSuccess": false, "code": 2580, "message":"숙박 예약 삭제여부는 Y, N으로 입력해주세요." },
    SIGNIN_WISH_STATUS_EMPTY: { "isSuccess": false, "code": 2581, "message":"위시리스트 상태값을 입력해주세요." },
    SIGNIN_WISH_STATUS_ERROR_TYPE: { "isSuccess": false, "code": 2582, "message":"위시리스트 여부는 Y, N으로 입력해주세요." },
    SIGNIN_REVIEW_STATUS_EMPTY: { "isSuccess": false, "code": 2583, "message":"리뷰 상태값을 입력해주세요." },
    SIGNIN_REVIEW_STATUS_ERROR_TYPE: { "isSuccess": false, "code": 2584, "message":"리뷰 삭제 여부는 Y, N으로 입력해주세요." },
    SIGNIN_NOTICE_MESSAGE_EMPTY: { "isSuccess": false, "code": 2585, "message":"알림 메세지를 입력해주세요." },
    SIGNIN_MESSAGE_ROOMIDX_EMPTY: { "isSuccess": false, "code": 2586, "message":"채팅방을 입력해주세요." },
    SIGNIN_MESSAGE_ROOMIDX_ERROR_FORM: { "isSuccess": false, "code": 2587, "message":"채팅방idx는 숫자만 입력해주세요." },
    SIGNIN_MESSAGE_EMPTY: { "isSuccess": false, "code": 2588, "message":"채팅 보낼 메세지를 입력해주세요." },

    USER_USERIDX_EMPTY : { "isSuccess": false, "code": 2700, "message": "userIdx를 입력해주세요." },
    USER_USERID_EMPTY : { "isSuccess": false, "code": 2701, "message": "userId를 입력해주세요." },
    USER_USERID_NOT_EXIST : { "isSuccess": false, "code": 2702, "message": "해당 회원이 존재하지 않습니다." },
    GOOGLE_TOKEN_NOT_EXIST : { "isSuccess": false, "code": 2703, "message": "맞지 않는 구글 토큰입니다." },

    // USER_USEREMAIL_EMPTY : { "isSuccess": false, "code": 2014, "message": "이메일을 입력해주세요." },
    // USER_USEREMAIL_NOT_EXIST : { "isSuccess": false, "code": 2015, "message": "해당 이메일을 가진 회원이 존재하지 않습니다." },
    USER_ID_NOT_MATCH : { "isSuccess": false, "code": 2751, "message": "유저 아이디 값을 입력해주세요." },
    HOST_ID_NOT_MATCH : { "isSuccess": false, "code": 2752, "message": "호스트 아이디 값을 입력해주세요." },
    PHOTO_ID_NOT_MATCH : { "isSuccess": false, "code": 2753, "message": "사진 아이디 값을 입력해주세요." },
    TRIP_ID_NOT_MATCH: { "isSuccess": false, "code": 2754, "message": "여행 아이디 값을 입력해주세요." },
    WISH_HOST_ID_NOT_MATCH: { "isSuccess": false, "code": 2755, "message": "위시할 호스트 아이디 값을 입력해주세요." },
    WISHLIST_ID_NOT_MATCH: { "isSuccess": false, "code": 2756, "message": "위시리스트 아이디 값을 입력해주세요." },
    MESSAGE_ID_NOT_MATCH: { "isSuccess": false, "code": 2757, "message": "메세지 아이디 값을 입력해주세요." },
    REVIEW_ID_NOT_MATCH: { "isSuccess": false, "code": 2758, "message": "리뷰 아이디 값을 입력해주세요." },
    NOTICE_ID_NOT_MATCH: { "isSuccess": false, "code": 2759, "message": "알림 아이디 값을 입력해주세요." },
    // USER_NICKNAME_EMPTY : { "isSuccess": false, "code": 2017, "message": "변경할 닉네임 값을 입력해주세요" },

    USER_STATUS_EMPTY : { "isSuccess": false, "code": 2800, "message": "회원 상태값을 입력해주세요" },

    // Response error
    SIGNUP_REDUNDANT_EMAIL : { "isSuccess": false, "code": 3001, "message":"중복된 이메일입니다." },
    SIGNUP_REDUNDANT_PHONE : { "isSuccess": false, "code": 3002, "message":"중복된 휴대폰 번호입니다." },
    SIGNUP_REDUNDANT_STATUS : { "isSuccess": false, "code": 3003, "message":"계정의 다른 상태값을 입력해주세요." },
    SIGNUP_REDUNDANT_HOST : { "isSuccess": false, "code": 3004, "message":"이미 등록된 호스트입니다." },
    SIGNUP_MESSAGE_ROOM_EXIST : { "isSuccess": false, "code": 3005, "message":"존재하지 않는 대화방입니다." },
    SIGNUP_REDUNDANT_USER_MESSAGE : { "isSuccess": false, "code": 3006, "message":"같은 유저에게 메시지를 보낼 수 없습니다." },
    // SIGNUP_REDUNDANT_PERSON : { "isSuccess": false, "code": 3004, "message":"이미 등록된 숙박 인원이 있습니다." },
    // SIGNUP_REDUNDANT_BEDROOM : { "isSuccess": false, "code": 3005, "message":"이미 등록된 침대 유형이 있습니다." },
    // SIGNUP_REDUNDANT_CATEGORY : { "isSuccess": false, "code": 3006, "message":"이미 등록된 숙박 카테고리가 있습니다." },
    // SIGNUP_REDUNDANT_LOCATION : { "isSuccess": false, "code": 3007, "message":"이미 등록된 숙박 위치가 있습니다." },
    // SIGNUP_REDUNDANT_RESERVATION : { "isSuccess": false, "code": 3008, "message":"이미 등록된 예약 설정이 있습니다." },
    // SIGNUP_REDUNDANT_PRICE : { "isSuccess": false, "code": 3009, "message":"이미 등록된 요금 설정이 있습니다." },
    SIGNUP_REDUNDANT_USER_RESERVATION : { "isSuccess": false, "code": 3010, "message":"이미 예약된 숙박 호스트입니다." },
    SIGNUP_REDUNDANT_WISHLIST_ISWISH : { "isSuccess": false, "code": 3011, "message":"이미 등록된 위시리스트 상태값입니다." },
    SIGNUP_HOST_NOT_REGISTER : { "isSuccess": false, "code": 3012, "message":"등록된 호스트가 없습니다. 호스트를 먼저 등록 해주세요." },
    SIGNUP_HOST_NOT_MATCH : { "isSuccess": false, "code": 3013, "message":"존재하지 않는 숙박 호스트 입니다." },
    SIGNUP_CATEGORY_NOT_REGISTER : { "isSuccess": false, "code": 3014, "message":"등록된 호스트 카테고리가 없습니다. 호스트 카테고리를 등록 해주세요." },
    SIGNUP_LOCATION_NOT_REGISTER : { "isSuccess": false, "code": 3015, "message":"등록된 호스트 위치가 없습니다. 호스트 위치를 등록 해주세요." },
    SIGNUP_AMENITIES_NOT_REGISTER : { "isSuccess": false, "code": 3016, "message":"등록된 호스트 편의시설이 없습니다. 호스트 편의시설을 등록 해주세요." },
    SIGNUP_PHOTO_NOT_REGISTER : { "isSuccess": false, "code": 3017, "message":"등록된 호스트 사진이 없습니다. 호스트 사진을 등록 해주세요." },
    SIGNUP_PHOTO_ERROR_TYPE: { "isSuccess": false, "code": 3018, "message":"삭제 입력만 가능합니다." },
    SIGNUP_RESERVATION_NOT_REGISTER : { "isSuccess": false, "code": 3019, "message":"등록된 예약 설정이 없습니다. 예약 설정을 등록 해주세요." },
    SIGNUP_HOST_NOT_MATCH_CATEGORY : { "isSuccess": false, "code": 3020, "message":"카테고리에 등록한 호스트가 없습니다." },
    SIGNUP_TRIP_NOT_REGISTER : { "isSuccess": false, "code": 3021, "message":"등록된 숙박 예약이 없습니다." },
    SIGNUP_REDUNDANT_TRIP_DELETE : { "isSuccess": false, "code": 3022, "message":"이미 삭제된 예약입니다." },
    SIGNUP_WISHLIST_NOT_REGISTER : { "isSuccess": false, "code": 3023, "message":"등록된 위시리스트가 없습니다. 위시리스트를 등록 해주세요." },
    SIGNUP_REDUNDANT_HOST_STATUS : { "isSuccess": false, "code": 3024, "message":"이미 삭제된 호스트입니다." },
    SEARCH_HOST_STATE_EMPTY : { "isSuccess": false, "code": 3025, "message":"해당 지역의 숙박호스트가 없습니다." },
    SIGNUP_REDUNDANT_WISHLIST : { "isSuccess": false, "code": 3026, "message":"이미 등록된 위시리스트입니다." },
    SIGNUP_MESSAGE_EXIST : { "isSuccess": false, "code": 3027, "message":"존재하지 않는 메시지입니다." },
    SIGNUP_REDUNDANT_MESSAGE_STATUS : { "isSuccess": false, "code": 3028, "message":"이미 삭제된 메시지입니다." },
    SIGNUP_REDUNDANT_REVIEW : { "isSuccess": false, "code": 3029, "message":"이미 등록된 리뷰입니다." },
    SIGNUP_REVIEW_EXIST : { "isSuccess": false, "code": 3030, "message":"존재하지 않는 리뷰입니다." },
    SIGNUP_NOTICE_EXIST : { "isSuccess": false, "code": 3031, "message": "존재하지 않는 알림 메세지입니다." },
    SIGNUP_REDUNDANT_NOTICE_STATUS : { "isSuccess": false, "code": 3032, "message":"이미 삭제된 알림입니다." },
    SIGNUP_REDUNDANT_NOTICE_MESSAGE : { "isSuccess": false, "code": 3033, "message":"이미 등록된 알림입니다." },
    SIGNUP_REDUNDANT_WISHLIST_STATUS : { "isSuccess": false, "code": 3034, "message":"이미 삭제된 위시리스트입니다." },
    SIGNUP_REDUNDANT_PHOTO_STATUS : { "isSuccess": false, "code": 3035, "message":"이미 삭제된 사진입니다." },


    SIGNIN_EMAIL_WRONG : { "isSuccess": false, "code": 3100, "message": "이메일이 없는 사용자입니다. 회원가입을 해주세요." },
    SIGNIN_PHONE_WRONG : { "isSuccess": false, "code": 3101, "message": "휴대폰 번호가 없는 사용자입니다. 회원가입을 해주세요." },
    SIGNIN_PASSWORD_WRONG : { "isSuccess": false, "code": 3102, "message": "비밀번호가 잘못 되었습니다." },
    SIGNIN_INACTIVE_ACCOUNT : { "isSuccess": false, "code": 3103, "message": "비활성화 된 계정입니다. 고객센터에 문의해주세요." },
    SIGNIN_WITHDRAWAL_ACCOUNT : { "isSuccess": false, "code": 3104, "message": "탈퇴 된 계정입니다. 고객센터에 문의해주세요." },


    //Connection, Transaction 등의 서버 오류
    DB_ERROR : { "isSuccess": false, "code": 4000, "message": "데이터 베이스 에러"},
    SERVER_ERROR : { "isSuccess": false, "code": 4001, "message": "서버 에러"},
 
 
}
